# Generated by Django 4.1.5 on 2023-03-08 00:54

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ("taggit", "0005_auto_20220424_2025"),
        ("article", "0003_articlepost_column"),
    ]

    operations = [
        migrations.AddField(
            model_name="articlepost",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to="article/%Y%m%d"),
        ),
        migrations.AddField(
            model_name="articlepost",
            name="tags",
            field=taggit.managers.TaggableManager(
                blank=True,
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
    ]
