# Generated by Django 4.1.5 on 2023-04-02 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0004_articlepost_avatar_articlepost_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="articlepost",
            name="likes",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
