# Generated by Django 4.1.5 on 2023-03-05 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("comment", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="articlecomment",
            old_name="article",
            new_name="article_related",
        ),
    ]
